name: "\U0001F41B Bug Report"
description: "Create a report to help us improve or fix something that is broken"
title: "[BUG]"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for opening a bug report!
        
        This template is designed to provide as much information about the bug as possible so we can go about squashing it!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Describe the steps we can take to see the bug
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please tell us any pertinent information about your environment that might help us. This could be browser, OS, package version, and so on.
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this are to highlight it and then dragging the files in.
      
