name: "\U0001F680 Feature request"
description: Suggest an new feature or a big change
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for opening a feature request!
        
        This template is designed to provide as much information about the feature as possible so we can go about developing it!
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: |
        A clear and concise description of why the proposed feature is needed and what problem it will fix.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like to have"
      description: |
        A clear and concise description of what you want to happen. This could include technical details.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: |
        Please provide details of alternative implementations you've considered or what will happen if this feature is not implemented.
    validations:
      required: true
  - type: textarea
    id: extras
    attributes:
      label: Anything else?
      description: |
        Add any other context about the feature request here.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
