name: Clean Jupyter Notebook Outputs

on: [workflow_call]

jobs:
  clean-notebook-outputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Check notebook outputs and metadata
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
